window.DreamOSModules = window.DreamOSModules || {};
window.DreamOSModules.ghost = {
    init() { console.log('👻 Ghost Mode Activated'); document.getElementById('ghost-dashboard').classList.add('active'); lucide.createIcons(); this.bindEvents(); },
    bindEvents() { const closeBtn = document.getElementById('close-ghost'); if (closeBtn) closeBtn.addEventListener('click', () => { document.getElementById('ghost-dashboard').classList.remove('active'); }); },
    toggleEruda() { const erudaBtn = document.getElementById('eruda-btn'); if (window.DreamOSModules.config.state && window.DreamOSModules.config.state.erudaActive) { if (typeof eruda !== 'undefined') eruda.destroy(); window.DreamOSModules.config.state.erudaActive = false; if (erudaBtn) erudaBtn.textContent = 'Inject Now'; } else { const script = document.createElement('script'); script.src = "https://cdn.jsdelivr.net/npm/eruda"; script.onload = function() { if (typeof eruda !== 'undefined') { eruda.init(); window.DreamOSModules.config.state.erudaActive = true; if (erudaBtn) erudaBtn.textContent = 'Destroy'; } }; document.body.appendChild(script); } },
    async checkOsint() { const user = document.getElementById('osint-input').value; const resultDiv = document.getElementById('osint-result'); if (!user) return; resultDiv.classList.remove('hidden'); resultDiv.textContent = `Searching ${user}...`; try { const res = await fetch(`https://api.github.com/users/${user}`); const data = await res.json(); if (data.login) { resultDiv.innerHTML = `✅ Found: ${data.login}<br>📍 Loc: ${data.location || 'N/A'}<br>🏢 Bio: ${data.bio || 'N/A'}`; } else { resultDiv.textContent = `❌ User ${user} tidak ditemukan.`; } } catch(e) { resultDiv.textContent = `❌ Gagal memuat data.`; } },
    copyNmap() { const target = document.getElementById('nmap-target').value || '127.0.0.1'; const cmd = `nmap -sV -sC ${target}`; this.copyText(cmd); },
    copyText(text) { navigator.clipboard.writeText(text).then(() => alert('✅ Copied!')).catch(() => alert('📋 Copy manual:\n' + text)); }
};
